### PR TITLE
refactor examples IFRS and banking_agent

### PR DESCRIPTION
**Pull request by siebenbrunner**

### CODE REVIEW

**Comment by rht** [comment]
@siebenbrunner you can rerun the travis test by doing these:
1. `git commit --amend --no-edit` (basically changes the timestamp of the commit)
2. `git push -f` for update origin/master with this commit with a new timestamp.

**Comment by rht** [comment]
Also, `git merge` is messy, before you did the rerunning the travis test, you can clean up the branch by doing these:
1. `git rebase -i HEAD~5` -- drop all the commits that do merge branch and fix merge commit
2. `git pull --rebase upstream master` -- this pulls the change from upstream/master and then reapplies the new commits i.e. "some fixes to get the old examples running again (not working)" and "get examples running again"
3. `git push -f`

**Comment by rht** [comment]
Actually, I have done these git plumbing things in #27 so you don't have to do them.

**Comment by DavoudTaghawiNejad** [comment]
Superseeded by pr #27 which is merged in.

**Pull request closed without merging**
